accounts/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views


app_name = 'accounts'


urlpatterns = [
    url(
        regex=r"^memberships/$",
        view=views.memberships,
        name="memberships"
    ),
    url(
        regex=r"^settings/$",
        view=views.account_settings,
        name="account_settings"
    ),
    url(
        regex=r'^(?P<sponsor_pk>\d+)/$',
        view=views.detail,
        name='detail'
    ),
]

authentication/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views


app_name = 'authentication'


urlpatterns = [
    url(
        regex=r"^login/$",
        view=views.auth_base_view,
        name="auth_base_view"
    ),
    url(
        regex=r"^login/complete/$",
        view=views.auth_login,
        name="auth_login"
    ),
    url(
        regex=r"^memberships/register/$",
        view=views.auth_register,
        name="auth_register"
    ),
    url(
        regex=r"^logout/$",
        view=views.auth_logout,
        name="auth_logout"
    ),
    url(
        regex=r"^password/forgot/$",
        view=views.password_reset,
        name="password_reset"
    ),
    url(
        regex=r"^password/reset/confirm/"
              r"(?P<uidb64>[0-9A-Za-z_\-]+)/"
              r"(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
        view=views.password_reset_confirm,
        name="password_reset_confirm"
    ),
]

billing/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views


app_name = 'billing'


urlpatterns = [
    url(
        regex=r'^checkout/(?P<event_pk>\d+)/$',
        view=views.checkout,
        name='checkout'
    ),
    url(
        regex=r'^update_auto_renew/$',
        view=views.update_auto_renew,
        name='update_auto_renew'
    ),
]

trip/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from . import views


admin.site.site_header = "TRIP Administration"
admin.site.site_title = "TRIP Administration"
admin.site.index_title = "TRIP"


urlpatterns = [
    # ADMIN
    url(
        r'^hidden/secure/trip/admin/',
        include(admin.site.urls)
    ),

    # GENERAL
    url(
        regex=r'^$',
        view=views.home,
        name='home'
    ),

    # ACCOUNTS
    url(
        r'^accounts/',
        include('accounts.urls', namespace='accounts')
    ),

    # AUTHENTICATION
    url(
        r'^auth/',
        include('authentication.urls', namespace='authentication')
    ),

    # BILLING
    url(
        r'^billing/',
        include('billing.urls', namespace='billing')
    ),

    # CONTACT
    url(
        r'^contact/',
        include('contact.urls', namespace='contact')
    ),

    # EVENTS
    url(
        r'^events/',
        include('events.urls', namespace='events')
    ),

    # SPONSORS
    url(
        regex=r'^sponsors/$',
        view=views.sponsors,
        name='sponsors'
    ),
]


if settings.DEBUG:
    urlpatterns += [] + static(settings.STATIC_URL,
                               document_root=settings.STATIC_ROOT)
    urlpatterns += [] + static(settings.MEDIA_URL,
                               document_root=settings.MEDIA_ROOT)
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

authentication/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

accounts/forms.py
"""
Glossary of accounts/forms.py:

- Account settings form
- MyUser change form (admin only)
"""

from __future__ import unicode_literals

try:
    from collections import OrderedDict
except ImportError:
    OrderedDict = None

from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.password_validation import validate_password
from django.db.models import Q
from django.utils.translation import ugettext_lazy as _

from .models import MyUser

# Create your forms here.


def clean_passwords(data, password1, password2):
    if password1 in data and password2 in data:
        if data[password1] != data[password2]:
            raise forms.ValidationError(
                _("You must type the same password each time."))
        validate_password(data[password2])
    return data[password2]


class AccountSettingsForm(forms.ModelForm):
    """A form used for users to update their account information."""
    email = forms.EmailField(
        label=_('Email'),
        widget=forms.EmailInput(),
        max_length=120
    )
    first_name = forms.CharField(
        label=_('First Name'),
        widget=forms.TextInput(),
        max_length=50
    )
    last_name = forms.CharField(
        label=_('Last Name'),
        widget=forms.TextInput(),
        max_length=50
    )
    password_new = forms.CharField(
        label=_("New Password"),
        widget=forms.PasswordInput(render_value=False),
        required=False
    )
    password_new_confirm = forms.CharField(
        label=_("New Password (again)"),
        widget=forms.PasswordInput(render_value=False),
        required=False
    )

    class Meta:
        model = MyUser
        fields = ('email', 'first_name', 'last_name',
                  'password_new', 'password_new_confirm',)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(AccountSettingsForm, self).__init__(*args, **kwargs)

    def clean_email(self):
        """Verify that the new email is not already taken."""
        value = self.cleaned_data['email'].lower()
        if self.initial.get('email') == value:
            return value
        if MyUser.objects.filter(
                Q(email__iexact=value) & ~Q(pk=self.user.pk)).exists():
            raise forms.ValidationError(
                _('This email is already taken. Please try a different one.'))
        return value

    def clean_password_new_confirm(self):
        if not self.cleaned_data['password_new_confirm'] == '':
            clean_passwords(data=self.cleaned_data,
                            password1="password_new",
                            password2="password_new_confirm")
        return self.cleaned_data['password_new_confirm']


class MyUserChangeForm(UserChangeForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field."""
    def __init__(self, *args, **kargs):
        super(MyUserChangeForm, self).__init__(*args, **kargs)
        # del self.fields['username']

    class Meta:
        model = MyUser
        fields = '__all__'

    def clean_email(self):
        """Verify that the new email is not already taken."""
        value = self.cleaned_data['email'].lower()
        if self.initial.get('email') == value:
            return value
        if MyUser.objects.filter(email__iexact=value).exists():
            raise forms.ValidationError(
                _('This email is already taken. Please try a different one.'))
        return value

accounts/views.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render
from django.views.decorators.cache import never_cache
from django.views.decorators.debug import sensitive_post_parameters

from billing.models import Customer, Plan, Subscription
from events.models import Event
from .forms import AccountSettingsForm
from .models import MyUser

# Create your views here.


@login_required
def detail(request, user_pk):
    user = get_object_or_404(MyUser, pk=user_pk)
    own_events = Event.objects.own(user=user)
    ctx = {
        'own_events': own_events,
        'user': user,
    }
    return render(request, 'accounts/detail.html', ctx)


@login_required
@never_cache
@sensitive_post_parameters()
def account_settings(request):
    user = request.user
    customer = Customer.objects.get(user=user)
    subscription = Subscription.objects.get(customer=customer)

    form = AccountSettingsForm(request.POST or None,
                               request.FILES or None,
                               instance=user, user=user)

    if request.method == 'POST' and form.is_valid():
        form.email = form.cleaned_data['email']
        password = form.cleaned_data['password_new_confirm']

        if password:
            current_user = form.user
            current_user.set_password(password)
            current_user.save()
            update_session_auth_hash(request, current_user)
        form.save()
        messages.success(request,
                         "You have successfully updated your profile.")
    ctx = {
        'form': form,
        'customer': customer,
        'subscription': subscription,
        'user': user,
    }
    return render(request, 'accounts/settings.html', ctx)


def memberships(request):
    plans = Plan.objects.active()
    return render(request, 'auth/memberships.html', {'plans': plans})

authentication/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.tokens import default_token_generator
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.views.decorators.cache import never_cache
from django.views.decorators.debug import sensitive_post_parameters

from accounts.models import MyUser
from billing.forms import StripeCreditCardForm
from billing.models import Customer, Plan, Subscription
from .forms import (LoginForm, SignupForm, PasswordResetForm,
                    PasswordResetTokenForm)

# Create your views here.


def auth_logout(request):
    logout(request)
    return redirect('home')


@never_cache
def auth_base_view(request):
    if request.user.is_authenticated():
        return redirect('home')
    next_url = request.GET.get('next', '/')
    return render(request, 'auth/login.html', {'next': next_url})


@never_cache
def auth_login(request):
    next_url = request.GET.get('next', '/')
    login_form = LoginForm(request.POST or None)
    if login_form.is_valid() and 'login_form' in request.POST:
        email = login_form.cleaned_data['email']
        password = login_form.cleaned_data['password']
        user = authenticate(email=email, password=password)

        if user is not None:
            login(request, user)
            return redirect(request.POST.get('next', 'home'))
        else:
            messages.warning(request, 'Username or password is incorrect.')
            return redirect('authentication:auth_base_view')
    ctx = {
        'login_form': login_form,
        'next': next_url,
    }
    return render(request, 'auth/_login_form.html', ctx)


@never_cache
def auth_register(request):
    form = SignupForm(request.POST or None, plan_id=request.POST['plan_id'])

    if request.method == 'POST' and form.is_valid():
        plan_id = request.POST['plan_id']
        plan = get_object_or_404(Plan, plan_id=plan_id)
        email = form.cleaned_data['email']
        password = form.cleaned_data['password_confirm']

        new_user = MyUser.objects.create_user(
            email=email,
            first_name=form.cleaned_data['first_name'],
            last_name=form.cleaned_data['last_name']
        )
        new_user.set_password(password)
        new_user.save()
        user = authenticate(email=email, password=password)

        if user is not None:
            login(request, user)
            cu = Customer.objects.create(user=user, account_balance=0)

            if plan.amount > 0:
                stripe_form = StripeCreditCardForm(request.POST,
                                                   user=user,
                                                   customer=cu)
                if stripe_form.is_valid():
                    sub = Subscription.objects.create(customer=cu, plan=plan)

                    if sub:
                        messages.success(request,
                                         'Your account has been successfully '
                                         'created.')
                        return redirect('home')
                elif stripe_form.errors:
                    for field in stripe_form:
                        for error in field.errors:
                            messages.error(request, error)
            elif plan.amount == 0:
                sub = Subscription.objects.create(customer=cu, plan=plan)

                if sub:
                    messages.success(request,
                                     'Your account has been successfully '
                                     'created.')
                    return redirect('home')

            user.delete()
            messages.error(request,
                           'There was an error creating your account.')
            return redirect('accounts:memberships')
    elif form.errors:
        for field in form:
            for error in field.errors:
                messages.error(request, error)
        return redirect('accounts:memberships')
    return render(request, 'auth/memberships.html', {'form': form})


def password_reset(request, from_email=settings.DEFAULT_FROM_EMAIL,
                   template_name='auth/password_reset_form.html',
                   email_template_name='auth/password_reset_email.html',
                   subject_template_name='Trip Reset Account Password',
                   password_reset_form=PasswordResetForm,
                   token_generator=default_token_generator,
                   html_email_template_name='auth/password_reset_email.html'):
    if request.user.is_authenticated():
        return redirect('home')
    else:
        if request.method == "POST":
            form = password_reset_form(request.POST)
            if form.is_valid():
                opts = {
                    'use_https': request.is_secure(),
                    'token_generator': token_generator,
                    'from_email': from_email,
                    'email_template_name': email_template_name,
                    'subject_template_name': subject_template_name,
                    'request': request,
                    'html_email_template_name': html_email_template_name,
                }
                form.save(**opts)

                messages.success(
                    request,
                    "If that email is registered to an account, "
                    "instructions for resetting your password "
                    "will be sent soon. Please make sure to check "
                    "your junk email/spam folder if you do not "
                    "receive an email.")
        else:
            form = password_reset_form()
        return render(request, template_name, {'form': form})


@sensitive_post_parameters()
@never_cache
def password_reset_confirm(request, uidb64=None, token=None,
                           token_generator=default_token_generator):
    assert uidb64 is not None and token is not None
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = MyUser._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, MyUser.DoesNotExist):
        user = None

    if user is not None and token_generator.check_token(user, token):
        validlink = True
        form = PasswordResetTokenForm(request.POST or None, user=user)
        if request.method == 'POST':
            if form.is_valid():
                form.save()
                messages.success(request, "Password reset successfully.")
                return redirect('home')
    else:
        validlink = False
        form = None
        messages.error(request, "Password reset unsuccessful")
    ctx = {
        'form': form,
        'validlink': validlink,
    }
    return render(request, 'auth/password_set.html', ctx)

templates/accounts/_auth_form.html
{% load staticfiles %}

<div class="module form-module">
    <div class="toggle">
        <i class="fa fa-times fa-pencil"></i>
        <div class="tooltip">Register</div>
    </div>
    <div class="form">
        <h2>Login to your account</h2>
        <form method="POST" action="{% url 'accounts:auth_login_register' %}">
            {% csrf_token %}
            <input type="email" placeholder="Email" name="email" required />
            <input type="password" placeholder="Password" name="password" required />
            <input type="hidden" name="next" value="{{ next }}" />
            <button type="submit" name="login_form">Login</button>
        </form>
    </div>
    <div class="form">
        <h2>Create an account</h2>
        <form method="POST" action="{% url 'accounts:auth_login_register' %}">
            {% csrf_token %}
            <input type="text" placeholder="Company" name="company_name" required />
            <input type="email" placeholder="Email" name="email" required />
            <input type="password" placeholder="Password" name="password" required />
            <input type="hidden" name="next" value="{{ next }}" />
            <button type="submit" name="register_form">Register</button>
        </form>
    </div>
    <a href="#">
        <div class="cta">Forgot your password?</div>
    </a>
</div>

templates/accounts/_authentication.html
{% load staticfiles %}

<div class="module form-module">
    <div class="toggle">
        <i class="fa fa-times fa-pencil"></i>
        <div class="tooltip">Register</div>
    </div>
    <div class="form">
        <h2>Login to your account</h2>
        <form method="POST" action="{% url 'accounts:auth_login_register' %}">
            {% csrf_token %}
            <input type="email" placeholder="Email" name="email" required />
            <input type="password" placeholder="Password" name="password" required />
            <input type="hidden" name="next" value="{{ next }}" />
            <button type="submit" name="login_form">Login</button>
        </form>
    </div>
    <div class="form">
        <h2>Create an account</h2>
        <form method="POST" action="{% url 'accounts:auth_login_register' %}">
            {% csrf_token %}
            <input type="text" placeholder="Company name" name="company_name" required />
            <input type="email" placeholder="Email" name="email" required />
            <input type="password" placeholder="Password" name="password" required />
            <input type="hidden" name="next" value="{{ next }}" />
            <button type="submit" name="register_form">Register</button>
        </form>
    </div>
    <a href="#">
        <div class="cta">
            Forgot your password?
        </div>
    </a>
</div>

templates/accounts/detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}{% endblock title %}

{% block content %}
  <h3>Events sponsored</h3>
  <!-- table -->
  <div id="demo">
    <div class="table-responsive-vertical shadow-z-1">
      <table id="table" class="table table-hover table-mc-orange">
        <thead>
          <tr>
            <th>Name</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Link</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          {% for event in own_events %}
            <tr>
              <td data-title="Name">{{ event.name }}</td>
              <td data-title="Start Date">{{ event.event_start_date }}</td>
              <td data-title="End Date">{{ event.event_end_date }}</td>
              <td data-title="Link">
                <a href="{{ event.get_absolute_url }}">View event</a>
              </td>
              <td data-title="Status">{{ event.event_status }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  <!-- /table -->
{% endblock content %}

templates/accounts/login_register.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %} / Authentication{% endblock title %}

{% block content %}
    <section style="margin-bottom: 49px;">
        {% include 'accounts/_auth_form.html' %}
    </section>
{% endblock content %}

templates/accounts/settings.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %} / Settings{% endblock title %}

{% block content %}
  <img id="page-loader" style="position:absolute; top:50%; left:50%; display:none;" src="{% static 'img/loader.svg' %}" alt="Loader" />

  <div class="col-md-8 col-lg-8">
    <form class="form-validation" method="POST" action="{% url 'accounts:account_settings' %}">
      {% csrf_token %}
      <div class="form-title-row">
        <h1>User Information</h1>
      </div>
      <div class="form-row {% if form.email.errors %}email-field{% endif %}">
        <label>
          <span>Email</span>
          <input type="email" name="email" value="{{ form.email.value }}" required />
        </label>
        <span class="form-valid-data-sign"><i class="fa fa-check"></i></span>
        <span class="form-invalid-data-sign"><i class="fa fa-close"></i></span>
        <span class="form-invalid-data-info"></span>
      </div>
      <div class="form-row {% if form.first_name.errors %}first-name-field{% endif %}">
        <label>
          <span>First name</span>
          <input type="text" name="first_name" value="{{ form.first_name.value }}" required />
        </label>
        <span class="form-valid-data-sign"><i class="fa fa-check"></i></span>
        <span class="form-invalid-data-sign"><i class="fa fa-close"></i></span>
        <span class="form-invalid-data-info"></span>
      </div>
      <div class="form-row {% if form.last_name.errors %}last-name-field{% endif %}">
        <label>
          <span>Last name</span>
          <input type="text" name="last_name" value="{{ form.last_name.value }}" required />
        </label>
        <span class="form-valid-data-sign"><i class="fa fa-check"></i></span>
        <span class="form-invalid-data-sign"><i class="fa fa-close"></i></span>
        <span class="form-invalid-data-info"></span>
      </div>
      <div class="form-row {% if form.password_new_confirm.errors %}password-field{% endif %}">
        <label>
          <span>New password</span>
          <input type="password" name="password_new" placeholder="New password" />
        </label>
        <span class="form-valid-data-sign"><i class="fa fa-check"></i></span>
        <span class="form-invalid-data-sign"><i class="fa fa-close"></i></span>
        <span class="form-invalid-data-info"></span>
      </div>
      <div class="form-row {% if form.password_new_confirm.errors %}password-field{% endif %}">
        <label>
          <span>Confirm password</span>
          <input type="password" name="password_new_confirm" placeholder="Confirm new password">
        </label>
        <span class="form-valid-data-sign"><i class="fa fa-check"></i></span>
        <span class="form-invalid-data-sign"><i class="fa fa-close"></i></span>
        <span class="form-invalid-data-info"></span>
      </div>
      <div class="form-row">
        <button type="submit">Update</button>
      </div>
    </form>
  </div>

  <div class="col-md-4 col-lg-4 sidebar-gutter">
    <br><br>
    <div class="sidebar-widget">
      <h3 class="sidebar-title">Membership Information</h3>
      <div class="widget-container">
        <p>
          <strong>Plan</strong>: {{ subscription.plan.name }}
        </p>
        <p>
          <strong>Start Date</strong>: {{ subscription.current_period_start }}
        </p>
        <p>
          <strong>End Date</strong>: {{ subscription.current_period_end }}
        </p>
        <p>
          <strong>Auto-Renew</strong>: <span style="margin-left:7px;"><input type="checkbox" id="auto-renew" {% if customer.auto_renew %}checked{% endif %}></span>
        </p>
        {% if not customer.auto_renew %}
          <small>
            <em>
              * Your membership will be deactivated on the end date above, and you will no longer be charged.
            </em>
          </small>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock content %}

{% block scripts %}
  <script>
      $(document).ready(function() {
          var errorField = $('.first-name-field');
          errorField.addClass('form-invalid-data');
          errorField.find('.form-invalid-data-info').text('{% for error in form.first_name.errors %}{{ error }}{% endfor %}');

          var errorField = $('.last-name-field');
          errorField.addClass('form-invalid-data');
          errorField.find('.form-invalid-data-info').text('{% for error in form.last_name.errors %}{{ error }}{% endfor %}');

          var errorField = $('.email-field');
          errorField.addClass('form-invalid-data');
          errorField.find('.form-invalid-data-info').text('{% for error in form.email.errors %}{{ error }}{% endfor %}');

          var errorField = $('.password-field');
          errorField.addClass('form-invalid-data');
          errorField.find('.form-invalid-data-info').text('{% for error in form.password_new_confirm.errors %}{{ error }}{% endfor %}');

          // var successField = $('.form-input-email-row');
          // successField.addClass('form-valid-data');
      });
      $("#auto-renew").click(function(e) {
          e.preventDefault();
          var t = $(this),
              a = $(e.target);
          $.ajax({
              type: "POST",
              url: "{% url 'billing:update_auto_renew' %}",
              data: {
                  csrfmiddlewaretoken: "{{ csrf_token }}"
              },
              dataType: "json",
              beforeSend: function() {
                  $("body").css({"opacity":"0.3", "background-color":"rgb(0, 0, 0)"});
                  $("page-loader").css({"opacity":"1.0"});
                  $('#page-loader').show();
              },
              complete: function(){
                  $('#page-loader').hide();
                  location.reload();
              },
              success: function(e) {

              },
              error: function() {
                  alert("Sorry, there was an error with your request. Please try again later.");
              },
          })
      });
  </script>
{% endblock scripts %}