accounts/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views


app_name = 'accounts'


urlpatterns = [
    url(
        regex=r"^memberships/$",
        view=views.memberships,
        name="memberships"
    ),
    url(
        regex=r"^settings/$",
        view=views.account_settings,
        name="account_settings"
    ),
    url(
        regex=r'^(?P<sponsor_pk>\d+)/$',
        view=views.detail,
        name='detail'
    ),
]

authentication/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views


app_name = 'authentication'


urlpatterns = [
    url(
        regex=r"^login/$",
        view=views.auth_base_view,
        name="auth_base_view"
    ),
    url(
        regex=r"^login/complete/$",
        view=views.auth_login,
        name="auth_login"
    ),
    url(
        regex=r"^memberships/register/$",
        view=views.auth_register,
        name="auth_register"
    ),
    url(
        regex=r"^logout/$",
        view=views.auth_logout,
        name="auth_logout"
    ),
    url(
        regex=r"^password/forgot/$",
        view=views.password_reset,
        name="password_reset"
    ),
    url(
        regex=r"^password/reset/confirm/"
              r"(?P<uidb64>[0-9A-Za-z_\-]+)/"
              r"(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
        view=views.password_reset_confirm,
        name="password_reset_confirm"
    ),
]

contact/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views


app_name = 'contact'


urlpatterns = [
    url(
        regex=r'^$',
        view=views.inquiry,
        name='inquiry'
    ),
    url(
        regex=r"^unsubscribe/"
              r"(?P<email>\w+|[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$",
        view=views.unsubscribe,
        name='unsubscribe'
    )
]

events/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views


app_name = 'events'


urlpatterns = [
    url(
        regex=r'^(?P<event_pk>\d+)/$',
        view=views.detail,
        name='detail'
    ),
    url(
        regex=r'^(?P<event_pk>\d+)/success/$',
        view=views.reg_success,
        name='reg_success'
    ),
    url(
        regex=r'^$',
        view=views.list,
        name='list'
    ),
]

trip/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from . import views


admin.site.site_header = "TRIP Administration"
admin.site.site_title = "TRIP Administration"
admin.site.index_title = "TRIP"


urlpatterns = [
    # ADMIN
    url(
        r'^hidden/secure/trip/admin/',
        include(admin.site.urls)
    ),

    # GENERAL
    url(
        regex=r'^$',
        view=views.home,
        name='home'
    ),

    # ACCOUNTS
    url(
        r'^accounts/',
        include('accounts.urls', namespace='accounts')
    ),

    # AUTHENTICATION
    url(
        r'^auth/',
        include('authentication.urls', namespace='authentication')
    ),

    # BILLING
    url(
        r'^billing/',
        include('billing.urls', namespace='billing')
    ),

    # CONTACT
    url(
        r'^contact/',
        include('contact.urls', namespace='contact')
    ),

    # EVENTS
    url(
        r'^events/',
        include('events.urls', namespace='events')
    ),

    # SPONSORS
    url(
        regex=r'^sponsors/$',
        view=views.sponsors,
        name='sponsors'
    ),
]


if settings.DEBUG:
    urlpatterns += [] + static(settings.STATIC_URL,
                               document_root=settings.STATIC_ROOT)
    urlpatterns += [] + static(settings.MEDIA_URL,
                               document_root=settings.MEDIA_ROOT)
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

templates/503.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Trip / Maintenance</title>

    <!-- Bootstrap -->
    <link href="{% static 'vendors/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">
    <!-- Custom Theme Style -->
    <link href="{% static 'custom/css/custom.min.css' %}" rel="stylesheet">

  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <!-- page content -->
        <div class="col-md-12">
          <div class="col-middle">
            <div class="text-center">
              <h1 class="error-number">503</h1>
              <h2>Temporarily Unavailable</h2>
              <p>
                We are currently making changes, and the website will be unvailable at this time. We apologize for any inconvenience.
              </p>
            </div>
          </div>
        </div>
        <!-- /page content -->
      </div>
    </div>

    <!-- jQuery -->
    <script src="{% static 'vendors/jquery/jquery.min.js' %}" type="text/javascript"></script>
    <!-- NProgress -->
    <script src="{% static 'vendors/nprogress/nprogress.js' %}" type="text/javascript"></script>
    <!-- Custom Theme Scripts -->
    <script src="{% static 'custom/js/custom.js' %}" type="text/javascript"></script>

  </body>
</html>

templates/_sidebar.html
{% load staticfiles %}

<div class="col-md-4 sidebar-gutter">
    <aside>

        <!-- account -->
        <div class="sidebar-widget">
            <h3 class="sidebar-title">Account</h3>
            <div class="widget-container">
                {% if not request.user.is_authenticated %}
                    {% include 'accounts/_auth_form.html' %}
                {% else %}
                    <h4>Logged in</h4>
                    <p><a href="{% url 'accounts:auth_logout' %}">Sign out</a></p>
                    <!-- show profile information -->
                {% endif %}
            </div>
        </div>
        <!-- /account -->

        <!-- about -->
        <div class="sidebar-widget">
            <h3 class="sidebar-title">About</h3>
            <div class="widget-container widget-about">
                <h4>Jamie Mooz</h4>
                <div class="author-title">Designer</div>
                <p>While everyone’s eyes are glued to the runway, it’s hard to ignore that there are major fashion moments on the front row too.</p>
            </div>
        </div>
        <!-- /about -->

        <!-- featured events -->
        <div class="sidebar-widget">
            <h3 class="sidebar-title">Featured Events</h3>
            <div class="widget-container">
                <article class="widget-post">
                    <div class="post-image">
                        <a href="post.html"><img src="{% static 'img/90x60-1.jpg' %}" alt=""></a>
                    </div>
                    <div class="post-body">
                        <h2><a href="post.html">The State of the Word 2014</a></h2>
                        <div class="post-meta">
                            <span><i class="fa fa-clock-o"></i> 2. august 2015</span>
                        </div>
                    </div>
                </article>
                <article class="widget-post">
                    <div class="post-image">
                        <a href="post.html"><img src="{% static 'img/90x60-2.jpg' %}" alt=""></a>
                    </div>
                    <div class="post-body">
                        <h2><a href="post.html">Why The Muppets Needs to Channel 30 Rock</a></h2>
                        <div class="post-meta">
                            <span><i class="fa fa-clock-o"></i> 2. august 2015</span>
                        </div>
                    </div>
                </article>
                <article class="widget-post">
                    <div class="post-image">
                        <a href="post.html"><img src="{% static 'img/90x60-3.jpg' %}" alt=""></a>
                    </div>
                    <div class="post-body">
                        <h2><a href="post.html">The State of the Word 2014</a></h2>
                        <div class="post-meta">
                            <span><i class="fa fa-clock-o"></i> 2. august 2015</span>
                        </div>
                    </div>
                </article>
                <article class="widget-post">
                    <div class="post-image">
                        <a href="post.html"><img src="{% static 'img/90x60-4.jpg' %}" alt=""></a>
                    </div>
                    <div class="post-body">
                        <h2><a href="post.html">Vintage-Inspired Finds for Your Home</a></h2>
                        <div class="post-meta">
                            <span><i class="fa fa-clock-o"></i> 2. august 2015</span>
                        </div>
                    </div>
                </article>
                <article class="widget-post">
                    <div class="post-image">
                        <a href="post.html"><img src="{% static 'img/90x60-5.jpg' %}" alt=""></a>
                    </div>
                    <div class="post-body">
                        <h2><a href="post.html">The State of the Word 2014</a></h2>
                        <div class="post-meta">
                            <span><i class="fa fa-clock-o"></i> 2. august 2015</span>
                        </div>
                    </div>
                </article>
            </div>
        </div>
        <!-- /featured events -->

        <!-- social links -->
        <div class="sidebar-widget">
            <h3 class="sidebar-title">Follow us!</h3>
            <div class="widget-container">
                <div class="widget-socials">
                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-instagram"></i></a>
                    <a href="#"><i class="fa fa-google-plus"></i></a>
                    <a href="#"><i class="fa fa-dribbble"></i></a>
                    <a href="#"><i class="fa fa-reddit"></i></a>
                </div>
            </div>
        </div>
        <!-- /social links -->

        <!-- sidebar-widget -->
        <div class="sidebar-widget">
            <h3 class="sidebar-title">Categories</h3>
            <div class="widget-container">
                <ul>
                    <li><a href="#">Fashion</a></li>
                    <li><a href="#">Art</a></li>
                    <li><a href="#">Design</a></li>
                    <li><a href="#">Featured</a></li>
                    <li><a href="#">Graphics</a></li>
                    <li><a href="#">Peoples</a></li>
                    <li><a href="#">Uncategorized</a></li>
                </ul>
            </div>
        </div>
    </aside>
</div>

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta name="description" content="">
    <meta name="author" content="Trip">
    <link rel="icon" href="favicon.ico">

    <title>
      Transaction Risk Insurance Professionals{% block title %}{% endblock title %}
    </title>

    <!-- Bootstrap -->
    <link href="{% static 'vendors/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">
    <!-- Custom Theme Style -->
    <link href="{% static 'custom/css/style.css' %}" rel="stylesheet">
    <!-- Extra stylesheets -->
    {% block stylesheets %}{% endblock stylesheets %}
    <!-- Extra in-line style -->
    {% block css %}{% endblock css %}
  </head>
  <body>
    {% spaceless %}
    <!-- navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              {% url 'home' as home_url %}
              {% url 'accounts:memberships' as memberships_url %}
              {% url 'events:list' as events_url %}
              {% url 'sponsors' as sponsors_url %}
              {% url 'contact:inquiry' as contact_url %}

              <li {% if request.path == home_url %} class="active" {% endif %}>
                <a href="{{ home_url }}">Home</a>
              </li>
              <li {% if request.path == memberships_url %} class="active" {% endif %}>
                <a href="{{ memberships_url }}">Memberships</a>
              </li>
              <li {% if request.path == events_url %} class="active" {% endif %}>
                <a href="{{ events_url }}">Events</a>
              </li>
              <li {% if request.path == sponsors_url %} class="active" {% endif %}>
                <a href="{{ sponsors_url }}">Sponsors</a>
              </li>
              <li {% if request.path == contact_url %} class="active" {% endif %}>
                <a href="{{ contact_url }}">Contact</a>
              </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">

              <!-- social links -->
              {% if socials_exist %}
                {% if facebook_username %}
                  <li>
                    <a href="https://www.facebook.com/{{ facebook_username }}">
                      <i class="fa fa-facebook"></i>
                    </a>
                  </li>
                {% endif %}
                {% if twitter_username %}
                  <li>
                    <a href="https://twitter.com/{{ twitter_username }}">
                      <i class="fa fa-twitter"></i>
                    </a>
                  </li>
                {% endif %}
                {% if instagram_username %}
                  <li>
                    <a href="https://www.instagram.com/{{ instagram_username }}">
                      <i class="fa fa-instagram"></i>
                    </a>
                  </li>
                {% endif %}
                {% if google_plus_username %}
                  <li>
                    <a href="https://plus.google.com/+{{ google_plus_username }}">
                      <i class="fa fa-google-plus"></i>
                    </a>
                  </li>
                {% endif %}
              {% endif %}
              <!-- /social links -->

              {% if request.user.is_authenticated and request.user.is_staff %}
                <li style="border-left: 1px solid #ccc;">
                  <a href="{% url 'accounts:account_settings' %}">
                    <i class="fa fa-gear"></i>
                  </a>
                </li>
                {% if request.user.is_authenticated and request.user.is_staff %}
                  <li>
                    <a href="{{ request.scheme }}://{{ request.get_host }}/hidden/secure/trip/admin/events/event/add/">
                      <i class="fa fa-plus"></i>
                    </a>
                  </li>
                {% endif %}
              {% endif %}
            </ul>
        </div>
      </div>
    </nav>
    <!-- /navbar -->

    <div class="container">
      <!-- Header content -->
      {% block header_content %}{% endblock header_content %}

      <!-- Body content -->
      <section>
        {% block content %}{% endblock content %}
      </section>
    </div>
    <!-- /.container -->

    <footer class="footer">
      <div class="footer-socials">
        {% if socials_exist %}
          {% if facebook_username %}
            <a href="https://www.facebook.com/{{ facebook_username }}">
              <i class="fa fa-facebook"></i>
            </a>
          {% endif %}
          {% if twitter_username %}
            <a href="https://twitter.com/{{ twitter_username }}">
              <i class="fa fa-twitter"></i>
            </a>
          {% endif %}
          {% if instagram_username %}
            <a href="https://www.instagram.com/{{ instagram_username }}">
              <i class="fa fa-instagram"></i>
            </a>
          {% endif %}
          {% if google_plus_username %}
            <a href="https://plus.google.com/+{{ google_plus_username }}">
              <i class="fa fa-google-plus"></i>
            </a>
          {% endif %}
        {% endif %}
      </div>

      <div class="footer-bottom">
        <i class="fa fa-copyright"></i> Copyright {% now 'Y' %}. All rights reserved.
      </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'vendors/jquery/jquery.min.js' %}" type="text/javascript"></script>
    <!-- Bootstrap -->
    <script src="{% static 'vendors/bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>
    <!-- NProgress -->
    <script src="{% static 'vendors/nprogress/nprogress.js' %}" type="text/javascript"></script>
    <!-- Noty -->
    <script src="{% static 'vendors/noty/packaged/jquery.noty.packaged.min.js' %}" type="text/javascript"></script>
    <!-- Custom theme scripts -->
    <script src="{% static 'custom/js/custom.js' %}" type="text/javascript"></script>
    <!-- Extra scripts -->
    {% block js %}{% endblock js %}
    <!-- Extra in-line JavaScript scripts -->
    {% block scripts %}{% endblock scripts %}

    <script type="text/javascript">
        $(document).ready(function(){
            // top banner messages
            {% if messages %}
                {% for message in messages %}
                    var n = noty({
                        theme: 'relax', // or 'defaultTheme'
                        type: '{% if "success" in message.tags %}success{% elif "info" in message.tags %}information{% elif "warning" in message.tags %}warning{% else %}error{% endif %}',
                        text: '{% if "safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}',
                        dismissQueue: true,
                        animation: {
                            open: {height: 'toggle'},
                            close: {height: 'toggle'},
                            easing: 'swing',
                            speed: 500 // opening & closing animation speed
                        },
                        timeout: 3000, // false
                        modal: true,
                        callback: {
                            onShow: function() {},
                            afterShow: function() {},
                            onClose: function() {},
                            afterClose: function() {},
                            onCloseClick: function() {},
                        },
                    });
                {% endfor %}
            {% endif %}
            // /top banner messages
        });
    </script>

    {% endspaceless %}
  </body>
</html>